Load models from s3 test
zendesk/serving pull request #4
Opened 2019-10-02 05:55 UTC by jkirkwoodzendesk

2019-10-21 05:30 UTC, fsat requested changes
@jkirkwoodzendesk - thanks for the good work 🙏 - the PR itself looks fine, but I think we should remove the log lines. We will be reloading and unloading models continuously, and we don't want the log files to be filled with loading and unloading models messages.

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/load_model_prediction_service_impl.cc
> +  LOG(INFO) << "Load Model " + m_name;
Should this be a debug, or can we even remove this logging - I'd imagine we will make a large call of `LoadPredict` so we don't want the log to be saturated with this entry.

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/load_model_prediction_service_impl.cc
> +            << " model_base_path: " << model_base_path;
Similarly, I think we'd like this to be on Debug level, or we don't log this at all - otherwise the logs will be filled with these entries.

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/server_core.cc
> +                << "\n\tplatform : " << config.model_platform();
I think we should remove this log entry as well

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/server_core.cc
> +          LOG(INFO) << "Copy model " + config.name() + " to new config";
I think we should remove this logging

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/server_core.cc
> +      LOG(INFO) << "Recreated config. Reloading..";
I think we should remove this logging

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/server_core.cc
> +      LOG(INFO) << "Reloading Done.";
I think we should remove this logging

2019-10-21 05:30 UTC, fsat commented on tensorflow_serving/model_servers/server_core.cc
> +    LOG(INFO) << "Unload attempt, model not found: " << model_name;
Maybe this should be warning?

2019-10-22 03:34 UTC, jkirkwoodzendesk commented
I'll remove the INFO logging, but we should still set env var TF_CPP_MIN_LOG_LEVEL=1 if we want to reduce logging

2019-10-22 05:40 UTC, fsat approved these changes

2019-10-23 03:59 UTC, merged